version: '3.3'
services:
    nginx:
        image: nginx
        ports:
            - '8080:80'
        volumes:
            - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './nginx/nginxconfig.io:/etc/nginx/nginxconfig.io'
            - './nginx/sites-enabled:/etc/nginx/sites-enabled'
            - './nginx/sites-available:/etc/nginx/sites-available'
    test0:
        image: nginxdemos/hello
    test1:
        image: nginxdemos/hello
    test2:    
        image: nginxdemos/hello
